import type { FishSeed } from "./fish-helpers";

export const fishD: FishSeed[] = [
  {
    slug: "neon-tetra", name: "Neon Tetra", sci: "Paracheirodon innesi", cat: "tetras",
    short: "The iconic nano fish — electric neon stripes that glow in a planted tank.",
    desc: "Neon tetras are one of the most beloved aquarium fish, with a brilliant blue stripe and glowing red underbelly. Peaceful shoalers that thrive in groups of 10+.",
    origin: "Amazon Basin", t: [22, 28], ph: [5.0, 7.0], diff: "beginner", agg: "peaceful",
    tank: 40, size: 3, life: "5–8 years", diet: "Micro-omnivore — flakes, micro-pellets, frozen daphnia",
    compat: "Peaceful community shoaler; perfect with rasboras, corydoras and dwarf cichlids.",
    price: 70, offer: 50, stock: 120, feat: true, trend: true, lock: 1036, kw: "neon,tetra,fish",
    tags: ["nano", "shoaling", "planted tank"],
  },
  {
    slug: "black-phantom-tetra", name: "Black Phantom Tetra", sci: "Hyphessobrycon megalopterus", cat: "tetras",
    short: "A moody, elegant tetra with smoky-black fins and a pearl-like shimmer.",
    desc: "Black phantom tetras are striking shoalers with a dark, ghostly beauty — males flaunt long, flowing black dorsal fins and flash silver body highlights.",
    origin: "South America", t: [22, 28], ph: [6.0, 7.5], diff: "beginner", agg: "peaceful",
    tank: 70, size: 4, life: "5 years", diet: "Omnivore — micro-pellets, flakes, frozen foods",
    compat: "Peaceful shoaler for community planted tanks; keep 6+.",
    price: 280, offer: 200, stock: 50, lock: 1037, kw: "black,phantom,tetra",
    tags: ["shoaling", "dark", "community"],
  },
  {
    slug: "hockey-stick-fish", name: "Hockey Stick Fish", sci: "Thayeria boehlkei", cat: "tetras",
    short: "A sleek, diagonally striped characin that swims at a distinctive angle.",
    desc: "The hockey stick tetra gets its name from the bold black line running from tail to mid-body. A hardy, active surface-dwelling shoaler.",
    origin: "South America", t: [22, 28], ph: [6.0, 7.5], diff: "beginner", agg: "peaceful",
    tank: 60, size: 6, life: "5 years", diet: "Omnivore — flakes, micro-pellets, live food",
    compat: "Peaceful shoaler; keep in groups of 6+ with other community fish.",
    price: 150, offer: 100, stock: 40, lock: 1038, kw: "hockey,stick,tetra",
    tags: ["shoaling", "unique"],
  },
  {
    slug: "silver-tip-fish", name: "Silver Tip Fish", sci: "Hasemania nana", cat: "tetras",
    short: "A tiny, copper-silver tetra with brilliant white-tipped fins.",
    desc: "Silver tip tetras are small, active shoalers with a warm copper body and eye-catching white fin tips. Hardy and full of energy, perfect for nano and community tanks.",
    origin: "Brazil", t: [22, 28], ph: [6.0, 7.0], diff: "beginner", agg: "peaceful",
    tank: 50, size: 3, life: "4–5 years", diet: "Omnivore — micro-flakes, small frozen foods",
    compat: "Active peaceful shoaler; keep 8+ for best behaviour.",
    price: 140, offer: 100, stock: 55, lock: 1039, kw: "silver,tip,tetra",
    tags: ["shoaling", "nano", "active"],
  },
  {
    slug: "blue-ram-fish", name: "Blue RAM Fish", sci: "Mikrogeophagus ramirezi", cat: "cichlids",
    short: "A jewel of the dwarf cichlid world — electric blue body with shimmering golden highlights.",
    desc: "Blue rams are stunning dwarf cichlids with an intense neon-blue body, red eyes and flowing fins. Peaceful for a cichlid and perfect for planted community tanks.",
    origin: "South America (Orinoco)", t: [25, 30], ph: [5.5, 7.0], diff: "beginner", agg: "peaceful",
    tank: 60, size: 6, life: "3–4 years", diet: "Omnivore — micro-pellets, frozen brine shrimp",
    compat: "Peaceful dwarf cichlid; pair with tetras, rasboras and corydoras.",
    price: 580, offer: 480, stock: 25, feat: true, lock: 1040, kw: "blue,ram,cichlid",
    tags: ["dwarf cichlid", "colourful", "community"],
  },
  {
    slug: "evjd-fish", name: "EVJD Fish", sci: "Rocio octofasciata (electric blue)", cat: "cichlids",
    short: "Electric Blue Jack Dempsey — a shimmering turquoise variant of the classic JD cichlid.",
    desc: "The EVJD (Electric Blue Jack Dempsey) is a striking electric-blue variant covered in iridescent turquoise speckles. A stunning centrepiece with the classic JD personality.",
    origin: "Central America (aquarium strain)", t: [24, 28], ph: [6.5, 7.5], diff: "beginner", agg: "semi_aggressive",
    tank: 200, size: 20, life: "10–15 years", diet: "Carnivore — cichlid pellets, prawns, frozen foods",
    compat: "Semi-aggressive; keep with medium-sized robust tankmates.",
    price: 900, offer: 750, stock: 15, imp: true, lock: 1041, kw: "electric,blue,jack,dempsey",
    tags: ["cichlid", "electric blue", "centrepiece"],
  },
  {
    slug: "thailand-import-oscar", name: "Thailand Import Oscar", sci: "Astronotus ocellatus (premium import)", cat: "cichlids",
    short: "A premium imported oscar strain with intensified colour and pattern from Thai breeders.",
    desc: "Premium Thailand-imported oscars selected for vivid red-orange marbling, clean patterning and robust form. These water dogs have all the personality of classic oscars with show-grade looks.",
    origin: "Thailand (imported)", t: [23, 28], ph: [6.0, 7.5], diff: "beginner", agg: "aggressive",
    tank: 300, size: 35, life: "12–15 years", diet: "Carnivore — pellets, prawns, insects",
    compat: "Keep alone or with large robust tankmates; will eat small fish.",
    price: 1200, offer: 900, stock: 10, imp: true, lock: 1042, kw: "thailand,oscar,cichlid",
    tags: ["imported", "premium", "centrepiece"],
  },
  {
    slug: "mountain-minnow", name: "Mountain Minno Fish", sci: "Tanichthys albonubes", cat: "angelfish-oddballs",
    short: "The hardy White Cloud Mountain minnow — bulletproof, colourful and coldwater-tolerant.",
    desc: "Mountain minnows are small, vibrant fish with red fins and a golden-green body stripe. Among the hardiest aquarium fish, thriving in unheated tanks and perfect for beginners.",
    origin: "China (White Cloud Mountain)", t: [16, 24], ph: [6.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 40, size: 4, life: "5–7 years", diet: "Omnivore — flakes, micro-pellets",
    compat: "Perfect peaceful shoaler; thrives in coldwater and tropical setups alike.",
    price: 280, offer: 200, stock: 60, lock: 1043, kw: "white,cloud,mountain,minnow",
    tags: ["shoaling", "coldwater", "beginner"],
  },
  {
    slug: "sawbwa-rasbora", name: "Sawbwa Rasbora Fish", sci: "Sawbwa resplendens", cat: "angelfish-oddballs",
    short: "The 'Asian rummynose' — a sleek silver and neon-blue nano fish from Myanmar.",
    desc: "Sawbwa rasboras are elegant, torpedo-shaped nano fish with a shimmering silver body and striking neon-blue head in males. A rare and beautiful shoaler for planted tanks.",
    origin: "Myanmar (Inle Lake)", t: [20, 26], ph: [7.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 60, size: 3, life: "3–5 years", diet: "Omnivore — micro-flakes, small frozen foods",
    compat: "Peaceful shoaler; keep 8+ in a planted tank with gentle tankmates.",
    price: 500, offer: 400, stock: 30, nw: true, lock: 1044, kw: "sawbwa,rasbora,fish",
    tags: ["nano", "rare", "shoaling"],
  },
  {
    slug: "silver-shark", name: "Silver Shark", sci: "Balantiocheilos melanopterus", cat: "sharks-suckers",
    short: "A sleek, torpedo-shaped silver beauty with striking black-and-white fins.",
    desc: "Silver sharks (bala sharks) are graceful, fast-swimming shoalers with a shimmering silver body and black-edged fins. Peaceful giants for large community tanks.",
    origin: "Southeast Asia", t: [24, 28], ph: [6.0, 7.5], diff: "beginner", agg: "peaceful",
    tank: 250, size: 30, life: "10+ years", diet: "Omnivore — flakes, pellets, frozen foods",
    compat: "Peaceful shoaler; keep 3+ in large tanks with similar-sized tankmates.",
    price: 350, offer: 280, stock: 25, lock: 1045, kw: "silver,shark,bala,fish",
    tags: ["shoaling", "large tank", "peaceful"],
  },
  {
    slug: "batik-snail", name: "Batik Snail", sci: "Neritina variegata", cat: "snails-invertebrates",
    short: "A beautifully patterned, algae-grazing snail with intricate batik-like shell markings.",
    desc: "Batik snails are hard-working, peaceful algae eaters with stunning shell patterns. Safe with all fish and plants, they keep glass and decor spotless without breeding in freshwater.",
    origin: "Southeast Asia", t: [22, 28], ph: [7.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 20, size: 3, life: "2–3 years", diet: "Herbivore — algae, biofilm, algae wafers",
    compat: "Peaceful with all fish; cannot breed in freshwater — no snail plagues.",
    price: 200, offer: 139, stock: 40, lock: 1046, kw: "batik,snail,aquarium",
    tags: ["algae eater", "cleaner", "invertebrate"],
  },
  {
    slug: "white-wizard-snail", name: "White Wizard Snail", sci: "Filopaludina martensi", cat: "snails-invertebrates",
    short: "A ghostly white, oversized freshwater snail — gentle, striking and utterly unique.",
    desc: "White wizard snails are large, ivory-white snails with a smooth, conical shell. Gentle giants that peacefully glide through the aquarium, adding a magical touch to any tank.",
    origin: "Southeast Asia", t: [22, 28], ph: [7.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 30, size: 5, life: "3–4 years", diet: "Omnivore — detritus, algae, snail pellets, blanched veg",
    compat: "Peaceful with all fish; safe with plants. A true conversation piece.",
    price: 180, offer: 150, stock: 30, lock: 1047, kw: "white,wizard,snail",
    tags: ["invertebrate", "unique", "cleaner"],
  },
  {
    slug: "apple-snail", name: "Apple Snail", sci: "Pomacea bridgesii", cat: "snails-invertebrates",
    short: "The classic golden-yellow aquarium snail — cheerful, chunky and a joy to watch.",
    desc: "Apple snails are large, bright yellow (or blue, purple) snails with a round, apple-shaped shell. Peaceful scavengers that add colour and character to community tanks.",
    origin: "South America", t: [22, 28], ph: [7.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 20, size: 6, life: "2–3 years", diet: "Omnivore — algae, detritus, blanched veg, snail pellets",
    compat: "Safe with all peaceful fish; avoid snail-eating loaches and puffers.",
    price: 60, offer: 30, stock: 50, lock: 1048, kw: "apple,snail,aquarium",
    tags: ["invertebrate", "colourful", "beginner"],
  },
  {
    slug: "striped-pumpkin-snail", name: "Striped Pumpkin Snail", sci: "Neritina sp.", cat: "snails-invertebrates",
    short: "A warm orange-and-striped nerite snail — like a tiny pumpkin cleaning your glass.",
    desc: "Striped pumpkin snails are striking orange-brown nerites with bold dark stripes across a rounded shell. Excellent algae eaters, safe with all fish and plants, and cannot overpopulate in freshwater.",
    origin: "Southeast Asia", t: [22, 28], ph: [7.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 20, size: 2, life: "2–3 years", diet: "Herbivore — algae, biofilm, algae wafers",
    compat: "Perfectly peaceful; cannot breed in freshwater. A beautiful utility snail.",
    price: 200, offer: 160, stock: 35, lock: 1049, kw: "striped,pumpkin,snail",
    tags: ["algae eater", "invertebrate", "cleaner"],
  },
];
