import type { FishSeed } from "./fish-helpers";

export const fishC: FishSeed[] = [
  {
    slug: "oranda-goldfish", name: "Oranda Goldfish", sci: "Carassius auratus (oranda)", cat: "goldfish-koi",
    short: "A regal goldfish crowned with a raspberry-like 'wen' head growth.",
    desc: "Orandas are graceful fancy goldfish with a rounded body, flowing fins and a distinctive fleshy head cap. Peaceful, hardy coldwater favourites.",
    origin: "China (aquarium strain)", t: [18, 24], ph: [6.5, 8.0], diff: "beginner", agg: "peaceful",
    tank: 100, size: 20, life: "10–15 years", diet: "Omnivore — goldfish pellets, veg, gel food",
    compat: "Keep with other fancy goldfish; avoid fast fin-nippers.",
    price: 200, offer: 160, stock: 30, feat: true, trend: true, lock: 1025, kw: "oranda,goldfish",
    tags: ["fancy goldfish", "coldwater", "beginner"],
  },
  {
    slug: "black-moor", name: "Black Moor", sci: "Carassius auratus (moor)", cat: "goldfish-koi",
    short: "A velvety black telescope-eyed goldfish with a gentle, endearing nature.",
    desc: "Black moors are jet-black fancy goldfish with protruding telescope eyes and flowing fins. Calm and slow-moving — a charming coldwater classic.",
    origin: "China (aquarium strain)", t: [18, 24], ph: [6.5, 8.0], diff: "beginner", agg: "peaceful",
    tank: 100, size: 18, life: "10–15 years", diet: "Omnivore — sinking pellets, veg",
    compat: "Pair with other slow fancy goldfish; poor eyesight means gentle tankmates.",
    price: 180, offer: 150, stock: 28, feat: true, lock: 1026, kw: "black,moor,goldfish",
    tags: ["fancy goldfish", "coldwater"],
  },
  {
    slug: "sk-gold", name: "S.K Gold", sci: "Carassius auratus (premium strain)", cat: "goldfish-koi",
    short: "A premium metallic-gold fancy goldfish selected for colour and form.",
    desc: "The S.K Gold is a high-grade goldfish strain prized for its rich, even golden sheen and balanced finnage — a standout in any coldwater display.",
    origin: "Imported strain", t: [18, 24], ph: [6.5, 8.0], diff: "beginner", agg: "peaceful",
    tank: 100, size: 20, life: "12 years", diet: "Omnivore — colour pellets, veg",
    compat: "Great with orandas, moors and other fancy goldfish.",
    price: 350, stock: 16, nw: true, imp: true, lock: 1027, kw: "goldfish,gold",
    tags: ["premium", "fancy goldfish", "imported"],
  },
  {
    slug: "koi-carp", name: "Koi Carp", sci: "Cyprinus rubrofuscus", cat: "goldfish-koi",
    short: "Living jewels of the pond — hardy, long-lived and endlessly collectable.",
    desc: "Koi are ornamental carp famed for their bold red, white, black and metallic patterns. Peaceful, intelligent and long-lived, they become tame enough to hand-feed.",
    origin: "Japan / East Asia", t: [15, 28], ph: [7.0, 8.5], diff: "intermediate", agg: "peaceful",
    tank: 500, size: 60, life: "25+ years", diet: "Omnivore — koi pellets, veg, gel food",
    compat: "Pond fish; keep in groups with goldfish in large volumes.",
    price: 250, offer: 200, stock: 40, feat: true, trend: true, lock: 1028, kw: "koi,carp,pond",
    tags: ["pond", "collectable", "long-lived"],
  },
  {
    slug: "betta-fighter", name: "Betta Fighter Fish", sci: "Betta splendens", cat: "bettas-gouramis",
    short: "The dazzling siamese fighter — flowing fins, jewel colours, huge personality.",
    desc: "Betta fighters are stunning labyrinth fish available in every colour and fin type. A single male makes a mesmerising centrepiece for a nano tank and interacts readily with its keeper.",
    care: "Keep one male per tank. Warm, gently filtered water and a lid (they breathe air and jump). Feed betta pellets and frozen treats.",
    origin: "Southeast Asia", t: [24, 30], ph: [6.0, 7.5], diff: "beginner", agg: "semi_aggressive",
    tank: 20, size: 6, life: "3–5 years", diet: "Carnivore — betta pellets, bloodworm",
    compat: "Males must be kept alone; avoid other long-finned or nippy fish.",
    price: 120, offer: 90, stock: 60, feat: true, trend: true, lock: 1029, kw: "betta,fighter,fish",
    tags: ["nano", "colourful", "centrepiece"],
  },
  {
    slug: "dwarf-gourami", name: "Dwarf Gourami", sci: "Trichogaster lalius", cat: "bettas-gouramis",
    short: "A shimmering, peaceful centrepiece in electric blue and flame red.",
    desc: "Dwarf gouramis are gentle labyrinth fish glowing with iridescent blue-and-red stripes. Perfect calm centrepieces for planted community tanks.",
    origin: "South Asia", t: [24, 28], ph: [6.0, 7.5], diff: "beginner", agg: "peaceful",
    tank: 60, size: 9, life: "4 years", diet: "Omnivore — flakes, pellets, frozen foods",
    compat: "Peaceful community fish; keep one male to avoid squabbles.",
    price: 130, offer: 110, stock: 35, feat: true, lock: 1030, kw: "dwarf,gourami,fish",
    tags: ["community", "colourful", "planted tank"],
  },
  {
    slug: "giant-gourami-white", name: "Giant Gourami (White)", sci: "Osphronemus goramy", cat: "bettas-gouramis",
    short: "A gentle giant — a large, intelligent gourami with a calm, curious nature.",
    desc: "The white giant gourami is a big, personable labyrinth fish that recognises its keeper and grows into an impressive, characterful centrepiece for large tanks.",
    origin: "Southeast Asia", t: [24, 30], ph: [6.5, 8.0], diff: "intermediate", agg: "semi_aggressive",
    tank: 400, size: 45, life: "15–20 years", diet: "Omnivore — pellets, veg, fruit",
    compat: "Peaceful for its size but eats small fish; house with large tankmates.",
    price: 400, stock: 9, avail: "low_stock", lock: 1031, kw: "giant,gourami,fish",
    tags: ["large tank", "intelligent"],
  },
  {
    slug: "angel-fish-breeding", name: "Angel Fish (Breeding Size)", sci: "Pterophyllum scalare", cat: "angelfish-oddballs",
    short: "Tall, elegant and mature — breeding-size angels ready to pair and spawn.",
    desc: "These breeding-size angelfish show the full, majestic finnage the species is famous for. Graceful and intelligent, they make a stately centrepiece and readily pair off.",
    origin: "Amazon Basin", t: [24, 29], ph: [6.0, 7.5], diff: "intermediate", agg: "semi_aggressive",
    tank: 150, size: 15, life: "10 years", diet: "Omnivore — flakes, pellets, frozen foods",
    compat: "Peaceful centrepiece; may eat very small fish and can be territorial when breeding.",
    price: 250, offer: 200, stock: 22, feat: true, trend: true, lock: 1032, kw: "angelfish,aquarium",
    tags: ["breeding size", "centrepiece", "elegant"],
  },
  {
    slug: "alligator-gar", name: "Alligator Gar", sci: "Atractosteus spatula", cat: "angelfish-oddballs",
    short: "A prehistoric predator with an armoured body and toothy, gator-like snout.",
    desc: "The alligator gar is a living fossil — a torpedo-shaped surface predator for the dedicated monster-fish keeper. Fascinating, hardy, and grows very large.",
    care: "Requires an enormous tank/pond as it grows. A tight lid is essential. Feed meaty foods.",
    origin: "North America", t: [22, 28], ph: [6.5, 8.0], diff: "expert", agg: "aggressive",
    tank: 2000, size: 120, life: "20+ years", diet: "Carnivore — fish, prawns, meaty foods",
    compat: "Predatory; only very large tankmates it cannot swallow.",
    price: 600, stock: 5, avail: "low_stock", imp: true, lock: 1033, kw: "gar,predator,fish",
    tags: ["monster fish", "predator", "prehistoric"],
  },
  {
    slug: "zebra-fish", name: "Zebra Fish", sci: "Danio rerio", cat: "angelfish-oddballs",
    short: "Tireless, striped little dashers that bring constant sparkle and motion.",
    desc: "Zebra danios are hardy, fast-moving shoalers striped in blue and gold. Bulletproof beginner fish that thrive in cooler community tanks and love a strong current.",
    origin: "South Asia", t: [18, 26], ph: [6.5, 7.5], diff: "beginner", agg: "peaceful",
    tank: 60, size: 5, life: "3–4 years", diet: "Omnivore — micro flakes, small frozen foods",
    compat: "Superb peaceful shoaler; keep in groups of 6+.",
    price: 40, offer: 30, stock: 100, nw: true, lock: 1034, kw: "zebra,danio,fish",
    tags: ["shoaling", "beginner", "active"],
  },
  {
    slug: "black-ghost-fish", name: "Black Ghost Fish", sci: "Apteronotus albifrons", cat: "angelfish-oddballs",
    short: "A mysterious, velvety-black knifefish that glides like a ribbon of shadow.",
    desc: "The black ghost knifefish is a captivating oddball — an elongated, jet-black nocturnal fish that swims in fluid, undulating waves and can be trained to feed from the hand.",
    origin: "South America", t: [23, 28], ph: [6.0, 7.5], diff: "advanced", agg: "peaceful",
    tank: 200, size: 40, life: "10–15 years", diet: "Carnivore — bloodworm, prawns, pellets",
    compat: "Peaceful but eats small fish; provide caves and dim lighting.",
    price: 400, offer: 340, stock: 10, feat: true, lock: 1035, kw: "black,ghost,knifefish",
    tags: ["oddball", "nocturnal", "unique"],
  },
];
