import type { FishSeed } from "./fish-helpers";

export const fishB: FishSeed[] = [
  {
    slug: "mexican-texas", name: "Mexican Texas", sci: "Herichthys cyanoguttatus", cat: "cichlids",
    short: "A pearl-speckled powerhouse cichlid with attitude and iridescent blue spots.",
    desc: "The Texas cichlid is covered in glittering blue-green spots over a grey body. Bold, intelligent and territorial — a true centrepiece for large aggressive setups.",
    origin: "Mexico / Texas", t: [20, 28], ph: [6.5, 7.5], diff: "advanced", agg: "aggressive",
    tank: 250, size: 30, life: "10–13 years", diet: "Omnivore — pellets, prawns, veg",
    compat: "Territorial; house with similarly sized robust cichlids.",
    price: 250, stock: 15, lock: 1013, kw: "texas,cichlid", tags: ["aggressive", "centrepiece"],
  },
  {
    slug: "red-parrot", name: "Red Parrot", sci: "Parrot Cichlid (hybrid)", cat: "cichlids",
    short: "The famously cheerful, round-bodied cichlid with a permanent 'smile'.",
    desc: "Red parrot cichlids are hardy hybrids beloved for their bright orange colour, chunky shape and comical beak-like mouth. Full of personality and easy to keep.",
    origin: "Man-made hybrid", t: [24, 28], ph: [6.5, 7.5], diff: "beginner", agg: "semi_aggressive",
    tank: 200, size: 20, life: "10–15 years", diet: "Omnivore — colour-enhancing pellets",
    compat: "Semi-aggressive but sociable; good with other medium cichlids.",
    price: 200, offer: 160, stock: 25, feat: true, trend: true, lock: 1014, kw: "parrot,cichlid",
    tags: ["colourful", "hardy", "beginner cichlid"],
  },
  {
    slug: "jaguar-fish", name: "Jaguar Fish", sci: "Parachromis managuensis", cat: "cichlids",
    short: "A stunning predatory cichlid patterned like a jaguar — bold and impressive.",
    desc: "The jaguar cichlid develops gorgeous black spotting over a golden body as it matures. A large, intelligent predator that recognises its keeper.",
    origin: "Central America", t: [25, 30], ph: [7.0, 8.5], diff: "advanced", agg: "aggressive",
    tank: 300, size: 35, life: "15 years", diet: "Carnivore — pellets, prawns, fish",
    compat: "Predatory and territorial; best in a large species or robust cichlid tank.",
    price: 300, stock: 10, avail: "low_stock", lock: 1015, kw: "jaguar,cichlid",
    tags: ["predator", "monster fish", "patterned"],
  },
  {
    slug: "red-spot-severum", name: "Red Spot Severum", sci: "Heros efasciatus", cat: "cichlids",
    short: "A gentle 'freshwater discus' dappled with warm red-gold speckles.",
    desc: "Red spot severums are peaceful, disc-shaped cichlids with a calm temperament and beautiful red flecking. A graceful centrepiece for larger community tanks.",
    origin: "Amazon Basin", t: [24, 29], ph: [5.5, 7.0], diff: "intermediate", agg: "semi_aggressive",
    tank: 250, size: 20, life: "10 years", diet: "Omnivore — pellets, veg, frozen foods",
    compat: "Relatively peaceful; pairs well with silver dollars and larger tetras.",
    price: 280, offer: 240, stock: 14, feat: true, lock: 1016, kw: "severum,cichlid",
    tags: ["peaceful cichlid", "centrepiece"],
  },
  {
    slug: "salvini-cichlid", name: "Salvini Cichlid", sci: "Trichromis salvini", cat: "cichlids",
    short: "One of the most colourful Central American cichlids — yellow, black and red.",
    desc: "The salvini is a dazzling yellow cichlid marked with bold black bars and red highlights, intensifying at breeding time. Feisty but manageable.",
    origin: "Central America", t: [22, 30], ph: [7.0, 8.0], diff: "intermediate", agg: "aggressive",
    tank: 200, size: 18, life: "10 years", diet: "Carnivore — pellets, prawns, insects",
    compat: "Territorial, especially when breeding; give space and tankmates of similar size.",
    price: 260, stock: 12, lock: 1017, kw: "salvini,cichlid", tags: ["colourful", "aggressive"],
  },
  {
    slug: "yellow-cichlid", name: "Yellow Cichlid", sci: "Labidochromis caeruleus", cat: "cichlids",
    short: "The 'electric yellow' — a glowing lemon cichlid from Lake Malawi.",
    desc: "Electric yellow labs are among the most peaceful mbuna, their intense lemon-yellow bodies edged with black fins lighting up hard-water, rocky aquascapes.",
    origin: "Lake Malawi, Africa", t: [24, 28], ph: [7.6, 8.6], diff: "intermediate", agg: "semi_aggressive",
    tank: 150, size: 10, life: "8–10 years", diet: "Omnivore — cichlid pellets, spirulina",
    compat: "Good with other peaceful mbuna in hard, alkaline water.",
    price: 220, offer: 180, stock: 30, feat: true, trend: true, lock: 1018, kw: "electric,yellow,cichlid",
    tags: ["african cichlid", "colourful", "hard water"],
  },
  {
    slug: "tricolour-cichlid", name: "Tricolour Cichlid", sci: "Cichlasoma festae", cat: "cichlids",
    short: "A fiery red-and-black beauty that blazes with colour when mature.",
    desc: "The tricolour (red terror) cichlid develops intense red flanks crossed with black bars — one of the most spectacular large cichlids for the serious keeper.",
    origin: "South America", t: [24, 29], ph: [6.5, 8.0], diff: "advanced", agg: "aggressive",
    tank: 350, size: 40, life: "15 years", diet: "Carnivore — pellets, prawns, fish",
    compat: "Very territorial when breeding; a big-tank showpiece.",
    price: 320, stock: 8, avail: "low_stock", lock: 1019, kw: "red,terror,cichlid",
    tags: ["aggressive", "large tank", "showpiece"],
  },
  {
    slug: "tiger-oscar", name: "Tiger Oscar", sci: "Astronotus ocellatus", cat: "cichlids",
    short: "The classic 'water dog' — a smart, interactive cichlid with tiger markings.",
    desc: "Tiger oscars are dark with vivid orange-red marbling and a false eyespot on the tail. Famously intelligent, they beg for food and learn their keeper. A definitive centrepiece fish.",
    care: "Big appetite and big waste output — strong filtration and regular water changes are essential.",
    origin: "Amazon Basin", t: [23, 28], ph: [6.0, 7.5], diff: "intermediate", agg: "aggressive",
    tank: 300, size: 35, life: "12–15 years", diet: "Carnivore — pellets, prawns, insects",
    compat: "Keep alone or with large robust tankmates; will eat small fish.",
    price: 280, offer: 230, stock: 20, feat: true, trend: true, lock: 1020, kw: "tiger,oscar,cichlid",
    tags: ["centrepiece", "intelligent", "predator"],
  },
  {
    slug: "veiltail-oscar", name: "Veiltail Oscar", sci: "Astronotus ocellatus (veiltail)", cat: "cichlids",
    short: "An oscar with flowing, extended fins for extra grace and drama.",
    desc: "The veiltail oscar carries all the personality of a classic oscar with elegant, elongated finnage that trails as it swims.",
    origin: "Amazon Basin (aquarium strain)", t: [23, 28], ph: [6.0, 7.5], diff: "intermediate", agg: "aggressive",
    tank: 300, size: 35, life: "12–15 years", diet: "Carnivore — pellets, prawns, insects",
    compat: "As per tiger oscar; long fins are prone to nipping — choose tankmates carefully.",
    price: 320, stock: 14, lock: 1021, kw: "oscar,cichlid,aquarium", tags: ["veiltail", "centrepiece"],
  },
  {
    slug: "red-oscar", name: "Red Oscar", sci: "Astronotus ocellatus (red)", cat: "cichlids",
    short: "A blazing red-and-black oscar — pure statement fish.",
    desc: "Red oscars display broad, intense red-orange over a dark body. Bold, personable and unmistakable — a favourite big-tank centrepiece.",
    origin: "Amazon Basin (aquarium strain)", t: [23, 28], ph: [6.0, 7.5], diff: "intermediate", agg: "aggressive",
    tank: 300, size: 35, life: "12–15 years", diet: "Carnivore — pellets, prawns, insects",
    compat: "Keep with large, robust fish only.",
    price: 300, offer: 260, stock: 16, feat: true, lock: 1022, kw: "red,oscar,cichlid",
    tags: ["red", "centrepiece", "predator"],
  },
  {
    slug: "albino-oscar", name: "Albino Oscar", sci: "Astronotus ocellatus (albino)", cat: "cichlids",
    short: "A creamy white-and-orange oscar with striking red eyes.",
    desc: "Albino oscars pair soft white bodies with orange marbling and ruby eyes — a beautiful, high-contrast variant of the beloved oscar.",
    origin: "Amazon Basin (aquarium strain)", t: [23, 28], ph: [6.0, 7.5], diff: "intermediate", agg: "aggressive",
    tank: 300, size: 35, life: "12–15 years", diet: "Carnivore — pellets, prawns, insects",
    compat: "Large robust tankmates only; big filtration needed.",
    price: 310, stock: 13, lock: 1023, kw: "albino,oscar,cichlid", tags: ["albino", "centrepiece"],
  },
  {
    slug: "flowerhorn-thailand", name: "Flowerhorn (Thailand Imported)", sci: "Flowerhorn (hybrid)", cat: "cichlids",
    short: "The king of ornamental cichlids — a nuchal-humped, pearl-studded legend.",
    desc: "This Thailand-imported flowerhorn is a premium show-grade hybrid famous for its large 'kok' head hump, bold flower-row markings and dazzling pearling. A living centrepiece that interacts with its keeper.",
    care: "Best kept singly in a large tank. Feed a quality colour-and-hump pellet diet with strong filtration.",
    origin: "Thailand (imported)", t: [26, 30], ph: [6.5, 7.8], diff: "advanced", agg: "aggressive",
    tank: 250, size: 30, life: "10–12 years", diet: "Carnivore — flowerhorn pellets, prawns",
    compat: "Highly territorial; almost always kept alone.",
    price: 1500, offer: 1200, stock: 6, avail: "low_stock", feat: true, trend: true, imp: true,
    lock: 1024, kw: "flowerhorn,cichlid", tags: ["imported", "premium", "showpiece", "hump"],
  },
];
