import type { FishSeed } from "./fish-helpers";

export const fishA: FishSeed[] = [
  {
    slug: "guppy", name: "Guppy", sci: "Poecilia reticulata", cat: "livebearers",
    short: "The world's most popular beginner fish — endlessly colourful, hardy and always active.",
    desc: "Guppies are vibrant livebearers that breed readily and thrive in community tanks. Males flaunt flowing, multi-coloured tails while females are larger and fuller-bodied. Available in a rainbow of strains.",
    care: "Keep in groups with more females than males. Stable, slightly hard water suits them best. Feed varied flakes and the occasional live/frozen treat for peak colour.",
    origin: "South America", t: [22, 28], ph: [6.8, 7.8], diff: "beginner", agg: "peaceful",
    tank: 40, size: 5, life: "2–3 years", diet: "Omnivore — flakes, micro-pellets, brine shrimp",
    compat: "Excellent community fish; avoid fin-nippers and large predators.",
    price: 40, offer: 30, stock: 120, feat: true, trend: true, nw: true, lock: 1001, kw: "guppy,fish",
    tags: ["community", "colourful", "breeds easily"],
    varieties: [
      { name: "Full Red Guppy", price: 45 }, { name: "Blue Moscow Guppy", price: 60 },
      { name: "Yellow Cobra Guppy", price: 50 }, { name: "Half-Black Guppy", price: 55 },
    ],
  },
  {
    slug: "molly", name: "Molly", sci: "Poecilia sphenops", cat: "livebearers",
    short: "Peaceful, adaptable livebearers with a friendly nature and a taste for algae.",
    desc: "Mollies are sociable and easy to keep, tolerating a wide range of conditions. They graze on algae and appreciate a little aquarium salt or hard water. Great for beginners.",
    origin: "Central America", t: [24, 28], ph: [7.0, 8.2], diff: "beginner", agg: "peaceful",
    tank: 60, size: 8, life: "3–5 years", diet: "Omnivore — flakes, veg matter, algae",
    compat: "Peaceful community; happy with guppies, platies and tetras.",
    price: 50, offer: 40, stock: 80, feat: true, lock: 1002, kw: "molly,fish",
    tags: ["community", "algae grazer"],
    varieties: [{ name: "Black Molly", price: 50 }, { name: "Dalmatian Molly", price: 55 }],
  },
  {
    slug: "platy", name: "Platy", sci: "Xiphophorus maculatus", cat: "livebearers",
    short: "Cheerful, low-maintenance splashes of colour for any community tank.",
    desc: "Platies are robust, peaceful livebearers available in sunset, red-wag and blue strains. They stay small, breed easily and are perfect first fish.",
    origin: "Central America", t: [22, 28], ph: [7.0, 8.0], diff: "beginner", agg: "peaceful",
    tank: 45, size: 6, life: "3 years", diet: "Omnivore — flakes, pellets, veg",
    compat: "Ideal community fish alongside guppies, mollies and corydoras.",
    price: 50, offer: 40, stock: 90, nw: true, lock: 1003, kw: "platy,fish",
    tags: ["community", "beginner"],
  },
  {
    slug: "colombian-tetra", name: "Colombian Tetra", sci: "Hyphessobrycon columbianus", cat: "tetras",
    short: "A larger, silver-and-red tetra that shoals boldly and shimmers under light.",
    desc: "Colombian tetras have silvery-blue bodies topped with striking red fins. Active and hardy, they show best in a group of six or more.",
    origin: "Colombia", t: [23, 28], ph: [5.5, 7.5], diff: "beginner", agg: "semi_aggressive",
    tank: 80, size: 6, life: "5 years", diet: "Omnivore — flakes, frozen foods",
    compat: "Keep in shoals; may nip long fins if kept in small numbers.",
    price: 60, stock: 60, lock: 1004, kw: "tetra,fish", tags: ["shoaling", "hardy"],
  },
  {
    slug: "veiltail-serpae-tetra", name: "Veiltail Serpae Tetra", sci: "Hyphessobrycon eques", cat: "tetras",
    short: "Fiery red shoaling tetras with elegant, flowing veil fins.",
    desc: "The veiltail serpae is a deep-red tetra with a dramatic black shoulder spot and extended finnage. Best in a tight group to spread its playful energy.",
    origin: "Amazon Basin", t: [22, 27], ph: [5.5, 7.5], diff: "beginner", agg: "semi_aggressive",
    tank: 70, size: 4, life: "5 years", diet: "Omnivore — micro-pellets, frozen bloodworm",
    compat: "Shoal of 8+; keep away from slow, long-finned tankmates.",
    price: 50, stock: 55, lock: 1005, kw: "serpae,tetra,fish", tags: ["shoaling", "red"],
  },
  {
    slug: "cardinal-tetra", name: "Cardinal Tetra", sci: "Paracheirodon axelrodi", cat: "tetras",
    short: "A living neon jewel — electric blue over brilliant red, from tip to tail.",
    desc: "The cardinal tetra is one of the most beautiful nano fish, its full-length red stripe outshining the neon tetra. Stunning in a densely planted, dimly lit aquascape.",
    origin: "Rio Negro, South America", t: [23, 28], ph: [4.5, 6.8], diff: "intermediate", agg: "peaceful",
    tank: 60, size: 3, life: "4–5 years", diet: "Micro-omnivore — small flakes, frozen daphnia",
    compat: "Peaceful shoaler; perfect with rasboras, corydoras and dwarf cichlids.",
    price: 70, offer: 55, stock: 100, feat: true, trend: true, lock: 1006, kw: "cardinal,tetra",
    tags: ["nano", "planted tank", "shoaling"],
  },
  {
    slug: "red-tail-catfish", name: "Red Tail Catfish", sci: "Phractocephalus hemioliopterus", cat: "catfish-loaches",
    short: "A charismatic monster catfish for the dedicated large-tank keeper.",
    desc: "The red tail catfish is a striking predator with a dark body, white belly and vivid orange-red tail. Cute as a juvenile but grows very large — for experienced keepers with big systems only.",
    care: "Requires a very large tank/pond as it matures. Feed meaty foods; avoid overfeeding. Powerful filtration essential.",
    origin: "Amazon Basin", t: [24, 30], ph: [6.0, 7.5], diff: "expert", agg: "aggressive",
    tank: 1000, size: 100, life: "15+ years", diet: "Carnivore — pellets, fish, prawns",
    compat: "Will eat anything it can swallow; house alone or with equally large fish.",
    price: 350, stock: 12, avail: "low_stock", imp: true, lock: 1007, kw: "redtail,catfish",
    tags: ["monster fish", "predator", "large tank"],
  },
  {
    slug: "dotted-catfish", name: "Dotted Catfish", sci: "Pimelodus pictus", cat: "catfish-loaches",
    short: "The lively 'pictus' — a silver, polka-dotted catfish that never stops exploring.",
    desc: "Dotted (pictus) catfish are sleek, silver and covered in black spots, with long whiskers. Active shoalers that patrol the tank day and night.",
    origin: "South America", t: [23, 27], ph: [6.0, 7.5], diff: "intermediate", agg: "peaceful",
    tank: 150, size: 12, life: "8 years", diet: "Omnivore — sinking pellets, frozen foods",
    compat: "Peaceful with medium fish; will eat very small tankmates.",
    price: 250, stock: 20, lock: 1008, kw: "pictus,catfish", tags: ["active", "shoaling"],
  },
  {
    slug: "corydoras", name: "Corydoras", sci: "Corydoras spp.", cat: "catfish-loaches",
    short: "Adorable, hard-working armoured catfish that keep the substrate spotless.",
    desc: "Corydoras are peaceful bottom-dwellers with endearing personalities. They forage in groups and add constant gentle activity to the lower tank.",
    origin: "South America", t: [22, 27], ph: [6.0, 7.5], diff: "beginner", agg: "peaceful",
    tank: 60, size: 6, life: "5–8 years", diet: "Omnivore — sinking pellets, wafers",
    compat: "Wonderful community cleaner; keep in groups of 6+.",
    price: 120, offer: 100, stock: 45, feat: true, lock: 1009, kw: "corydoras,catfish",
    tags: ["cleaner", "community", "shoaling"],
  },
  {
    slug: "tiger-loach", name: "Tiger Loach", sci: "Syncrossus hymenophysa", cat: "catfish-loaches",
    short: "A boldly striped, snail-hunting loach full of character.",
    desc: "Tiger loaches sport dramatic dark bands over a golden body. Social and playful, they help control pest snails and enjoy caves and driftwood.",
    origin: "Southeast Asia", t: [24, 30], ph: [6.0, 7.5], diff: "intermediate", agg: "semi_aggressive",
    tank: 150, size: 20, life: "10 years", diet: "Omnivore — pellets, snails, frozen foods",
    compat: "Keep in groups; can be boisterous with timid fish.",
    price: 180, stock: 18, lock: 1010, kw: "loach,fish", tags: ["snail control", "striped"],
  },
  {
    slug: "rainbow-shark", name: "Rainbow Shark", sci: "Epalzeorhynchos frenatum", cat: "sharks-suckers",
    short: "A sleek charcoal body with fiery red fins — a striking, territorial showpiece.",
    desc: "Rainbow sharks (not true sharks) are active algae-grazers with jet-black bodies and vivid red-orange fins. An eye-catching centrepiece for larger community tanks.",
    origin: "Southeast Asia", t: [24, 28], ph: [6.5, 7.5], diff: "intermediate", agg: "semi_aggressive",
    tank: 120, size: 15, life: "8 years", diet: "Omnivore — sinking foods, algae, veg",
    compat: "Territorial with its own kind; keep one per tank with mid/top dwellers.",
    price: 150, offer: 120, stock: 30, feat: true, lock: 1011, kw: "rainbow,shark,fish",
    tags: ["algae grazer", "centrepiece"],
    varieties: [{ name: "Red-Fin Rainbow Shark", price: 150 }, { name: "Albino Rainbow Shark", price: 170 }],
  },
  {
    slug: "white-albino-sucker", name: "White Albino Sucker", sci: "Hypostomus plecostomus (albino)", cat: "sharks-suckers",
    short: "A hard-working albino pleco that grazes algae off glass and decor.",
    desc: "The albino sucker (pleco) is a pale, peaceful algae eater with a suckermouth. It clings to surfaces and keeps the tank clean, becoming quite large over time.",
    origin: "South America", t: [22, 30], ph: [6.5, 7.8], diff: "beginner", agg: "peaceful",
    tank: 150, size: 30, life: "10–15 years", diet: "Herbivore — algae wafers, veg, driftwood",
    compat: "Peaceful; provide driftwood and hiding spots. Grows large.",
    price: 90, offer: 75, stock: 40, nw: true, lock: 1012, kw: "pleco,albino,fish",
    tags: ["algae eater", "cleaner"],
  },
];
